package com.mobiloitte.notification.enums;

public enum MessageType {

	LOGIN, SUBSCRIBE_ORDER_BOOK, SUBSCRIBE_TRADE_HISTORY, UNSUBSCRIBE_ORDER_BOOK, UNSUBSCRIBE_TRADE_HISTORY,
	SUBSCRIBE_TICKER, UNSUBSCRIBE_TICKER, TICKER_UPDATE, ORDER_BOOK_UPDATE, TRADE_HISTORY_UPDATE
}
