package com.mobiloitte.usermanagement.enums;

public enum Authority {

	USER_MANAGEMENT, HOT_COLD_LIMIT_MANAGEMENT, FEE_MANAGEMENT, WALLET_MANAGEMENT, TRADE_MANAGEMENT, KYC_MANAGEMENT,
	STATIC_CONTENT, BASIC_TRADE_MANAGEMENT, FIAT_MANAGEMENT, MARKET_MANAGEMENT, TRANSACTION_MANAGEMENT, ROLE_SUBADMIN,
	STAFF_MANAGEMENT, DASHBOARD, LOGS_MANAGEMENT, ADVERTISEMENTS, TICKET_MANAGEMENT, DISPUTE_MANAGEMENT, SETTINGS,
	BANK_MANAGEMENT,XINDIA_MANAGEMENT,FAQ_MANAGEMENT,FUND_MANAGEMENT,FEEDBACK_MANAGEMENT,ESCROW_MANAGEMENT,EXCHANGE_MANAGEMENT

}