package com.mobiloitte.p2p.content.enums;

public enum Authority {
	USER_MANAGEMENT,
	HOT_COLD_LIMIT_MANAGEMENT,
	FEE_MANAGEMENT,
	WALLET_MANAGEMENT,
	TRADE_MANAGEMENT,
	KYC_MANAGEMENT,
	STATIC_CONTENT,
	REFERENCE_MANAGEMENT,
	BASIC_TRADE_MANAGEMENT,
	FIAT_MANAGEMENT,
	MARKET_MANAGEMENT,
	TRANSACTION_MANAGEMENT,
	NEWS_MANAGEMENT,
	
}